server:
  port: 80




eureka:
  client:
     register-with-eureka: false
     service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
pagehelper: #pagehelper分页插件配置
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

