server:
  port: 80

eureka:
  client:
     register-with-eureka: false
     service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
pagehelper: #pagehelper分页插件配置
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
spring:
    datasource:
        driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
        url: jdbc:mysql://116.62.157.132:3306/springcrm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC    # 数据库名称
        username: root
        password: zking216@
